# GitHub Action to build and push Docker image to Google Artifact Registry
#
# This workflow:
# - Builds a Docker image from the repository
# - Tags it with 'latest' and the commit SHA
# - Pushes to Google Cloud Artifact Registry
# - Deploys the latest image in Google Cloud Run
#
# Setup required:
# 1. GCP: Create service account in IAM & Admin > Service Accounts
# 2. GCP: Grant "Artifact Registry Writer" role to the service account to be able to push the image
# 3. GCP: Grant "Cloud Run Admin" role to the service account to be able to deploy the service
# 4. GCP: Create and download JSON key for the service account
# 5. GitHub: Add the JSON key as repository secret named 'GCP_SA_KEY'


name: Build and Push Docker Image to GCP

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  IMAGE_NAME: tennis-booking-assistant
  GCP_REPO_NAME: tennis-app-repo
  GCP_PROJECT: tennis-booking-assistant
  GCP_REGION: europe-west3

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker to use gcloud as credential helper
        run: |
          gcloud auth configure-docker ${{ env.GCP_REGION }}-docker.pkg.dev

      - name: Build Docker image
        run: |
          docker build -t ${{ env.IMAGE_NAME }} .

      - name: Tag Docker image
        run: |
          docker tag ${{ env.IMAGE_NAME }} ${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT }}/${{ env.GCP_REPO_NAME }}/${{ env.IMAGE_NAME }}:latest
          docker tag ${{ env.IMAGE_NAME }} ${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT }}/${{ env.GCP_REPO_NAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Push Docker image
        run: |
          docker push ${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT }}/${{ env.GCP_REPO_NAME }}/${{ env.IMAGE_NAME }}:latest
          docker push ${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT }}/${{ env.GCP_REPO_NAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy tennis-booking-assistant \
            --image=${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT }}/${{ env.GCP_REPO_NAME }}/${{ env.IMAGE_NAME }}:latest \
            --region=${{ env.GCP_REGION }} \
            --platform=managed \
